export const Ciudad = Object.freeze({
  acacias: 'Acacías',
  aguachica: 'Aguachica',
  arauca: 'Arauca',
  armenia: 'Armenia',
  barranquilla: 'Barranquilla',
  bello: 'Bello',
  bogota: 'Bogotá D.C.',
  bucaramanga: 'Bucaramanga',
  buenaventura: 'Buenaventura',
  calarca: 'Calarcá',
  cali: 'Cali',
  cartagena: 'Cartagena',
  caruru: 'Carurú',
  cerete: 'Cereté',
  chinchina: 'Chinchiná',
  cienaga: 'Ciénaga',
  codazzi: 'Agustín Codazzi',
  condoto: 'Condoto',
  corozal: 'Corozal',
  cucuta: 'Cúcuta',
  cumaribo: 'Cumaribo',
  doncello: 'El Doncello',
  dosquebradas: 'Dosquebradas',
  duitama: 'Duitama',
  envigado: 'Envigado',
  espinal: 'Espinal',
  florencia: 'Florencia',
  floridablanca: 'Floridablanca',
  fundacion: 'Fundación',
  garzon: 'Garzón',
  giron: 'Girón',
  granada: 'Granada',
  honda: 'Honda',
  ibague: 'Ibagué',
  ipiales: 'Ipiales',
  istmina: 'Istmina',
  laChorrera: 'La Chorrera',
  laDorada: 'La Dorada',
  laHormiga: 'La Hormiga',
  laPrimavera: 'La Primavera',
  leticia: 'Leticia',
  magangue: 'Magangué',
  maicao: 'Maicao',
  malambo: 'Malambo',
  manizales: 'Manizales',
  medellin: 'Medellín',
  mitu: 'Mitú',
  mocoa: 'Mocoa',
  montenegro: 'Montenegro',
  monteria: 'Montería',
  neiva: 'Neiva',
  ocaña: 'Ocaña',
  palmira: 'Palmira',
  pamplona: 'Pamplona',
  pasto: 'Pasto',
  pazDeAriporo: 'Paz de Ariporo',
  pereira: 'Pereira',
  pitalito: 'Pitalito',
  popayan: 'Popayán',
  providencia: 'Providencia',
  puertoAsis: 'Puerto Asís',
  puertoCarreño: 'Puerto Carreño',
  puertoNarino: 'Puerto Nariño',
  puertoTejada: 'Puerto Tejada',
  quibdo: 'Quibdó',
  riohacha: 'Riohacha',
  sahagun: 'Sahagún',
  sampues: 'Sampués',
  sanAndres: 'San Andrés',
  sanJuan: 'San Juan del Cesar',
  santaCatalina: 'Santa Catalina',
  santaMarta: 'Santa Marta',
  santanderDeQuilichao: 'Santander de Quilichao',
  santaRosa: 'Santa Rosa de Cabal',
  sanVicente: 'San Vicente del Caguán',
  saravena: 'Saravena',
  sincelejo: 'Sincelejo',
  sogamoso: 'Sogamoso',
  soledad: 'Soledad',
  sopo: 'Sopo',
  facatativa: 'Facatativa',
  tame: 'Tame',
  taraira: 'Taraira',
  tumaco: 'Tumaco',
  tunja: 'Tunja',
  turbaco: 'Turbaco',
  valledupar: 'Valledupar',
  villanueva: 'Villanueva',
  villavicencio: 'Villavicencio',
  yopal: 'Yopal',
});
