export const Departamento = Object.freeze({
  amazonas: 'Amazonas',
  antioquia: 'Antioquia',
  arauca: 'Arauca',
  atlantico: 'Atlántico',
  bolivar: 'Bolívar',
  boyaca: 'Boyacá',
  caldas: 'Caldas',
  caqueta: 'Caquetá',
  casanare: 'Casanare',
  cauca: 'Cauca',
  cesar: 'Cesar',
  choco: 'Choco',
  cordoba: 'Cordoba',
  cundinamarca: 'Cundinamarca',
  huila: 'Huila',
  laGuajira: 'La Guajira',
  magdalena: 'Magdalena',
  meta: 'Meta',
  narinio: 'Nariño',
  norteDeSantander: 'Norte de Santander',
  putumayo: 'Putumayo',
  quindio: 'Quindío',
  risaralda: 'Risalralda',
  SanAndresProvidencia: 'San Andrés y Providencia',
  santander: 'Santander',
  sucre: 'Sucre',
  tolima: 'Tolima',
  valleDelCauca: 'Valle del Cauca',
  vaupes: 'Vaupés',
  vichada: 'Vichada',
});
